# Generated by Django 5.1.6 on 2025-03-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier', models.CharField(max_length=255)),
                ('stock', models.IntegerField()),
                ('material', models.CharField(max_length=100)),
                ('delivery_time', models.CharField(max_length=50)),
            ],
        ),
    ]
