# Generated by Django 5.1.4 on 2025-05-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_productreview_rating_delete_productrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
